const ERROR_CODES = Object.freeze({
  // General Server Errors
  SERVER_ERROR: "SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CAST_ERROR: "CAST_ERROR",
  DUPLICATE_KEY: "DUPLICATE_KEY",

  // Authentication & Authorization
  AUTH_FAILED: "AUTH_FAILED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ACCESS_DENIED: "ACCESS_DENIED",

  JWT_INVALID: "JWT_INVALID",
  JWT_EXPIRED: "JWT_EXPIRED",
  TOKEN_MISSING: "TOKEN_MISSING",

  // File Upload

  UPLOAD_ERROR: "UPLOAD_ERROR",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",

  // Custom Application Errors
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  MISSING_FIELDS: "MISSING_FIELDS",
  NOT_ALLOWED: "NOT_ALLOWED",
});

module.exports = ERROR_CODES;
